version: '3.1'

services:
  web:
    image: caddy/caddy:v2.0.0-beta.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - config:/config/caddy
      - data:/data/caddy

volumes:
  data:
    driver: local
  config:
    driver: local
