version: '3.1'

services:
  web:
    image: hairyhenderson/hairyhenderson.ca:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - config:/config/caddy
      - data:/data/caddy

volumes:
  data:
    driver: local
  config:
    driver: local
