version: '3.1'

services:
  web:
    image: hairyhenderson/hairyhenderson.ca:latest
    labels:
      - "traefik.port=2015"
      - "traefik.frontend.rule=Host:hairyhenderson.ca,www.hairyhenderson.ca"
      - "traefik.tags=web"

  frontend:
    image: traefik:1.5-alpine
    command: |-
      --web --web.readonly
      --docker --docker.domain=hairyhenderson.ca --docker.constraints='tag==web'
      --logLevel=WARN
      --acme --acme.email=dhenderson@gmail.com --acme.ondemand
      --acme.httpchallenge.entrypoint="http"
      --acme.entrypoint=https --acme.storage=/certs/acme.json
      --acme.domains='hairyhenderson.ca,api.hairyhenderson.ca,www.hairyhenderson.ca'
      --entryPoints='Name:https Address::443 TLS'
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --defaultentrypoints='http,https'
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - certStorage:/certs

volumes:
  certStorage:
    driver: local
