version: '3.1'

services:
  web:
    image: hairyhenderson/hairyhenderson.ca:latest
    labels:
      - "traefik.port=2015"
      - "traefik.frontend.rule=Host:hairyhenderson.ca,www.hairyhenderson.ca"
      - "traefik.tags=web"
    

  frontend:
    image: traefik:1.5-alpine
    command: |-
      --web --web.readonly
      --docker --docker.domain=hairyhenderson.ca --docker.constraints='tag==web'
      --logLevel=WARN
      --acme --acme.email=dhenderson@gmail.com --acme.ondemand
      --acme.httpchallenge.entrypoint="http"
      --acme.entrypoint=https --acme.storage=/certs/acme.json
      --acme.domains='hairyhenderson.ca,api.hairyhenderson.ca,www.hairyhenderson.ca'
      --entryPoints='Name:https Address::443 TLS'
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --defaultentrypoints='http,https'
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - certStorage:/certs

  api_gw:
    image: kong:0.10
    depends_on:
      - kongdb
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=kongdb"
    labels:
      - "traefik.port=8000"
      - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.hairyhenderson.ca"
      - "traefik.tags=web"

  kongdb:
    image: postgres:9.6
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - pgVolume:/var/lib/postgresql/data/pgdata

volumes:
  certStorage:
    driver: local
  pgVolume:
    driver: local
