version: '2'

services:
  web:
    restart: always
    image: hairyhenderson/hairyhenderson.ca:latest
    labels:
      - "traefik.port=2015"
      - "traefik.frontend.rule=Host:hairyhenderson.ca,www.hairyhenderson.ca"
      - "traefik.tags=web"

  frontend:
    restart: always
    image: traefik
    command: |-
      --web --web.readonly
      --docker --docker.domain=hairyhenderson.ca --docker.constraints='tag==web'
      --logLevel=DEBUG
      --acme --acme.email=dhenderson@gmail.com --acme.ondemand
      --acme.entrypoint=https --acme.storageFile=/certs/acme.json
      --acme.domains='hairyhenderson.ca,api.hairyhenderson.ca,www.hairyhenderson.ca,blog.hairyhenderson.ca'
      --entryPoints='Name:https Address::443 TLS'
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --defaultentrypoints='http,https'
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - certStorage:/certs

  api_gw:
    restart: always
    image: mashape/kong
    links:
      - kongdb
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=kongdb"
    labels:
      - "traefik.port=8000"
      - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.hairyhenderson.ca"
      - "traefik.tags=web"
    ports:
      - "127.0.0.1:8001:8001"

  kongdb:
    restart: always
    image: postgres:9.4
    environment:
      - POSTGRES_USER
      - POSTGRES_DB

volumes:
  certStorage:
    driver: local
